extends: airbnb-base
env:
  browser: true
plugins:
  - import
rules:
  no-use-before-define: off
  no-nested-ternary: off
  no-new: off # pikaday
  prefer-rest-params: off
  no-param-reassign: 
    - error
    - props: false
